### ISSUE TITLE
[1.18.2] java.lang.NullPointerException: Cannot read field "f_120146_" because the return value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by wertercatt** [TheComputerizer/Music-Triggers#56] opened 2022-06-17 03:41 UTC
**Describe the bug**
The game randomly crashed, and the crash report indicated this mod as the culprit.

**To Reproduce**
Steps to reproduce the behavior: Unknown.

**Additional context**
See log here: https://mclo.gs/2zhTCXl

**Comment by TheComputerizer** [comment] 2022-06-17 04:00
Closing this as it is a duplicate of #41 and #54 

This is generally due to the name of the song that tried not matching anything from the within the song folder

**Closed by TheComputerizer** 2022-06-17 04:00 UTC

**Comment by wertercatt** [comment] 2022-06-17 04:15
> Closing this as it is a duplicate of #41 and #54 
> 
> 
> 
> This is generally due to the name of the song that tried not matching anything from the within the song folder.
> 
> 
> 
> After looking at your log before the crash occurred there is a problem with your "night" song

Fair enough. I'll send in an issue report on the Bliss tracker so you hopefully stop getting duplicate reports

**Comment by Vazkii** [comment] 2022-06-22 19:50
Here's the config used in the pack in question. What's the issue here? https://github.com/VazkiiMods/Bliss/blob/main/config/MusicTriggers/musictriggers.toml#L161-L171

**Comment by TheComputerizer** [comment] 2022-06-22 20:42
From a glance there doesn't seem to be an issue with the config itself so it is most likely the song itself or a weird incompatibility with something else. Does the song work on its own in a separate instance with just music triggers?

**Comment by wertercatt** [comment] 2022-06-23 05:55
My config is unchanged from Bliss. And I can play night.ogg just fine outside of the game

**Comment by TheComputerizer** [comment] 2022-06-23 09:11
Weird, but at least it won't be a problem anymore once 6.0 is released. Until then, future comments can go on #54
