### ISSUE TITLE
[1.19.2Fabric] Server startup crash

### ISSUE THREAD

**Issue by JackSpidy** [TheComputerizer/Music-Triggers#100] opened 2023-03-28 07:32 UTC
**Describe the bug**
Server barely gets anywhere in starting before this error is spat out:
`[00:28:42] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'musictriggers'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.17.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.17.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric.jar:0.11.2]
Caused by: java.lang.RuntimeException: Unable to create file directory at config\MusicTriggers! Music Triggers is unable to load any further.
	at mods.thecomputerizer.musictriggers.MusicTriggers.onInitialize(MusicTriggers.java:36) ~[Music-Triggers-1.19.2-fabric-6.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]
	... 8 more`

**To Reproduce**
Start a fabric 1.19.2 server with both Music-Triggers-1.19.2-fabric-6.1 and theimpossiblelibrary-1.19.2-fabric-0.2.3

**Additional context**
Crash happens when the mod is both a part of my larger modpack and on its own.

full log file -
[latest.log](https://github.com/TheComputerizer/Music-Triggers/files/11086578/latest.log)

**Comment by JackSpidy** [comment] 2023-03-28 07:36
#32 seems to be similar to this issue as well.

**Comment by TheComputerizer** [comment] 2023-03-28 08:04
It's unrelated to client stuff getting loaded. The problem is most likely that the mod is assuming the config folder already exists when it tries to make the MusicTriggers folder. Creating a config folder in your server files manually should work until that gets fixed

**Comment by JackSpidy** [comment] 2023-03-28 08:16
> It's unrelated to client stuff getting loaded. The problem is most likely that the mod is assuming the config folder already exists when it tries to make the MusicTriggers folder. Creating a config folder in your server files manually should work until that gets fixed

I've created a config folder, and it created a MusicTriggers folder on launch, along with a registration.toml, still the same crash message though.

**Comment by TheComputerizer** [comment] 2023-03-28 08:24
If it created the file successfully, that means it crashed at least a little bit later on. Can you send the new crash report?

**Comment by JackSpidy** [comment] 2023-03-28 08:24
[latest.log](https://github.com/TheComputerizer/Music-Triggers/files/11087050/latest.log)

**Comment by TheComputerizer** [comment] 2023-03-28 08:31
Looks like a packet receiver is getting registered on the wrong side which will need an update to get fixed. That will be in 6.2

**Comment by JackSpidy** [comment] 2023-03-28 08:34
Alright, great! thanks for your help/time.

**Comment by TheComputerizer** [comment] 2023-04-26 10:52
This has been fixed in 6.2

**Closed as completed by TheComputerizer** 2023-04-26 10:52 UTC
Labels: bug, pending
