### ISSUE TITLE
[1.16.5] Music Recorder no longer works.

### ISSUE THREAD

**Issue by bauerbach** [TheComputerizer/Music-Triggers#72] opened 2022-11-30 22:23 UTC
**Describe the bug**
The Music Recorder is completely broken in 5.4 on version 1.16.5. The item in the GUI shows up correctly, but when placed, the block just shows up as a pink and black cube and right-clicking it does nothing.

**To Reproduce**

1. Place a Music Recorder from the Creative menu.
2. It will display as a pink and black cube in the world. Try right-clicking on it.

**Additional context**
Game Version: 1.16.5 (Forge)
Mod Version: 5.4-hf

**Comment by TheComputerizer** [comment] 2022-12-01 01:52
The texture is just broken but it should still work as intended. Right click a blank record into it when a song is playing and it will get recorded

**Comment by TheComputerizer** [comment] 2023-01-05 14:21
This has been fixed in 6.0

**Closed by TheComputerizer** 2023-01-05 14:21 UTC
Labels: more information needed
