### ISSUE TITLE
 The game cannot start!

### ISSUE THREAD

**Issue by Qee1y** [TheComputerizer/Music-Triggers#145] opened 2023-10-27 02:36 UTC
forge 1.19.2 , mod_musictriggers-1.19.2-6.3

Problem during loading phase!

[crash-2023-10-27_10.31.21-fml.txt](https://github.com/TheComputerizer/Music-Triggers/files/13184448/crash-2023-10-27_10.31.21-fml.txt)

**Comment by TheComputerizer** [comment] 2023-10-27 18:00
Closing since this is a duplicate of #142

**Closed as completed by TheComputerizer** 2023-10-27 18:00 UTC
