### ISSUE TITLE
[1.12] Crash when using debug menu

### ISSUE THREAD

**Issue by CalaMariGold** [TheComputerizer/Music-Triggers#143] opened 2023-10-16 19:14 UTC
Enable debug menu, then every now and then when I click reload config after making changes in the cfg file, the game crashes

https://mclo.gs/Seqq9CG

**Comment by CalaMariGold** [comment] 2023-10-16 21:25
This also occurs on player death

**Comment by TheComputerizer** [comment] 2023-11-02 18:53
Seems like the debug info didn't like one of your GUI classes. I'll add a catch for that

**Comment by TheComputerizer** [comment] 2023-11-03 00:29
Fixed in 6.3.1

**Closed as completed by TheComputerizer** 2023-11-03 00:29 UTC
Labels: bug, pending

**Comment by TheComputerizer** [comment] 2023-11-03 19:59
Ok so the issue isn't actually fixed since for some reason I decided to log the error with the same method that crashes it, but the root of the issue is The Impossible library so I've moved the issue over there TheComputerizer/The-Impossible-Library#15
