### ISSUE TITLE
[Fabric 1.19.2-fabric-6.0] Crash when using menu.

### ISSUE THREAD

**Issue by pokesmells** [TheComputerizer/Music-Triggers#89] opened 2023-03-09 16:28 UTC
**Describe the bug**
Opened the GUi for music triggers and clicked a button, then got served with a client side crash 😭
**To Reproduce**
1. Install the mod
2. Open the GUI
3. Crash when using the GUI.

**Additional context**
https://mclo.gs/OK68l01 - Crash Logs
https://mclo.gs/ksoRnnv - Latest Logs, should include mods.

**Comment by TheComputerizer** [comment] 2023-03-09 20:37
Duplicate of #87 - The playback screen is currently unimplemented

**Closed as not planned by TheComputerizer** 2023-03-09 20:37 UTC
