### ISSUE TITLE
[1.12] Startup crash

### ISSUE THREAD

**Issue by Aeron216** [TheComputerizer/Music-Triggers#30] opened 2022-05-06 06:14 UTC
My instance crashes within seconds after updating from **4.1-hf** to **5.2-hf2**
I made sure that the old config folder was deleted.

[debug](https://gist.github.com/Aeron216/8c2ba8705794c55f76e6945a0b8a3a73)

[latest](https://gist.github.com/Aeron216/9b78145da35a6382a9cc27e5810b63d6)

[mod list](https://gist.github.com/Aeron216/0e9d1f38559a480d0538a88c2d3a0d84)

**Comment by TheComputerizer** [comment] 2022-05-06 08:51
Is your version of mixinbooter up to date?

**Comment by Aeron216** [comment] 2022-05-06 09:06
This one?
https://www.curseforge.com/minecraft/mc-mods/mixin-booter

It is:
![image](https://user-images.githubusercontent.com/54506307/167101261-8c2cc72c-a493-4b7e-b996-1823ac4d690f.png)

However my MixinBootstrap isnt because the latest version, 1.1.0, crashes my whole instance in a similar manner. So I'm still running 1.0.5

**Comment by Aeron216** [comment] 2022-05-06 11:40
Bingo
Crashed when I added Sledgehammer.

![image](https://user-images.githubusercontent.com/54506307/167124262-44849fd9-b29c-4752-b4c8-145ec93f166d.png)
![image](https://user-images.githubusercontent.com/54506307/167124290-6be994fa-74a7-4d1d-beeb-6b46b15a9dee.png)

Uh, I'm going to have to check my options because I do make use of it. Could just be one setting so I'll have to figure it out.

[My sledgehammer config](https://gist.github.com/Aeron216/c5a42a2d0df9b96cbd35376e1b8ed719)

**Comment by TheComputerizer** [comment] 2022-05-06 12:13
You may want to post an issue to sledgehammer. Ill leave this issue open for now until there is some more information, but I do not think the problem is stemming from Music Triggers. It's likely some mixin compatibility issue

**Comment by TheComputerizer** [comment] 2022-05-06 12:21
Ok I actually did some more testing and it seems like it does crash with only Music Triggers, MixinBooter, and Sledgehammer installed. I will do some more testing and see if it is something fixable from my end

**Comment by TheComputerizer** [comment] 2022-05-06 13:23
I figured out the problem and it will be fixed in 5.3

**Comment by TheComputerizer** [comment] 2022-05-07 08:59
Fixed in 5.3

**Closed by TheComputerizer** 2022-05-07 08:59 UTC
