### ISSUE TITLE
The server successfully starts and loads the world but crashes immediately afterward.

### ISSUE THREAD

**Issue by Hlwyefeng** [TheComputerizer/Music-Triggers#189] opened 2024-10-07 18:22 UTC
[02:19:46] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Music Triggers (musictriggers)

Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at mods.thecomputerizer.musictriggers.config.ConfigRedirect.<init>(ConfigRedirect.java:39) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannel.getRedirect(ServerChannel.java:40) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannel.<init>(ServerChannel.java:55) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannelManager.initialize(ServerChannelManager.java:25) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.MusicTriggers.serverStarting(MusicTriggers.java:100) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639) ~[cleanroom-0.2.3-alpha.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:270) ~[guava-33.2.1-jre.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(MixinCleanroomLoadController.java:303) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(MixinCleanroomLoadController.java:281) ~[LoadController.class:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:270) ~[guava-33.2.1-jre.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(MixinCleanroomLoadController.java:217) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:802) ~[Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:298) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:307) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1802) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:259) ~[foundation-0.13.9.jar:?]
	at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:266) ~[foundation-0.13.9.jar:?]
	at mods.thecomputerizer.musictriggers.config.ConfigRedirect.<init>(ConfigRedirect.java:39) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannel.getRedirect(ServerChannel.java:40) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannel.<init>(ServerChannel.java:55) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannelManager.initialize(ServerChannelManager.java:25) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.MusicTriggers.serverStarting(MusicTriggers.java:100) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639) ~[cleanroom-0.2.3-alpha.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:270) ~[guava-33.2.1-jre.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(MixinCleanroomLoadController.java:303) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(MixinCleanroomLoadController.java:281) ~[LoadController.class:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:270) ~[guava-33.2.1-jre.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(MixinCleanroomLoadController.java:217) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:802) ~[Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:298) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:307) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1802) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@2b3b1124 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:261) ~[cleanroom-0.2.3-alpha.jar:?]
	at top.outlands.foundation.TransformerDelegate.lambda$fillTransformerHolder$1(TransformerDelegate.java:150) ~[foundation-0.13.9.jar:?]
	at top.outlands.foundation.boot.ActualClassLoader.runTransformers(ActualClassLoader.java:331) ~[foundation-0.13.9.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:68) ~[foundation-0.13.9.jar:?]
	at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:243) ~[foundation-0.13.9.jar:?]
	at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:266) ~[foundation-0.13.9.jar:?]
	at mods.thecomputerizer.musictriggers.config.ConfigRedirect.<init>(ConfigRedirect.java:39) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannel.getRedirect(ServerChannel.java:40) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannel.<init>(ServerChannel.java:55) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannelManager.initialize(ServerChannelManager.java:25) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.MusicTriggers.serverStarting(MusicTriggers.java:100) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639) ~[cleanroom-0.2.3-alpha.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:270) ~[guava-33.2.1-jre.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(MixinCleanroomLoadController.java:303) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(MixinCleanroomLoadController.java:281) ~[LoadController.class:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:270) ~[guava-33.2.1-jre.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(MixinCleanroomLoadController.java:217) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:802) ~[Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:298) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:307) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1802) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: Attempted to load class bib for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[cleanroom-0.2.3-alpha.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:257) ~[cleanroom-0.2.3-alpha.jar:?]
	at top.outlands.foundation.TransformerDelegate.lambda$fillTransformerHolder$1(TransformerDelegate.java:150) ~[foundation-0.13.9.jar:?]
	at top.outlands.foundation.boot.ActualClassLoader.runTransformers(ActualClassLoader.java:331) ~[foundation-0.13.9.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:68) ~[foundation-0.13.9.jar:?]
	at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:243) ~[foundation-0.13.9.jar:?]
	at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:266) ~[foundation-0.13.9.jar:?]
	at mods.thecomputerizer.musictriggers.config.ConfigRedirect.<init>(ConfigRedirect.java:39) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannel.getRedirect(ServerChannel.java:40) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannel.<init>(ServerChannel.java:55) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.server.channels.ServerChannelManager.initialize(ServerChannelManager.java:25) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at mods.thecomputerizer.musictriggers.MusicTriggers.serverStarting(MusicTriggers.java:100) ~[musictriggers-1.12.2-6.3.1.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639) ~[cleanroom-0.2.3-alpha.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:270) ~[guava-33.2.1-jre.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(MixinCleanroomLoadController.java:303) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(MixinCleanroomLoadController.java:281) ~[LoadController.class:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111) ~[guava-33.2.1-jre.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:270) ~[guava-33.2.1-jre.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(MixinCleanroomLoadController.java:217) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:802) ~[Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:298) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:307) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1802) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by TheComputerizer** [comment] 2024-10-07 21:45
Server based configs aren't functional in 1.12.2 currently. Remove all files except for `registration.toml` from `config/MusicTriggers` on the server for now

**Comment by TheComputerizer** [comment] 2024-10-07 21:47
Oh this is a duplicate of #150

**Closed as completed by TheComputerizer** 2024-10-07 21:47 UTC
Labels: duplicate

**Comment by Hlwyefeng** [comment] 2024-10-08 00:04
Thank you, the issue has been resolved
