### ISSUE TITLE
[1.18.2 6.0 Release Crash]

### ISSUE THREAD

**Issue by 0BLIQU3** [TheComputerizer/Music-Triggers#91] opened 2023-03-10 00:42 UTC
**Describe the bug**
Start-up crash: Upon running Music Triggers alongside the Illuminations (Forge) mod, Minecraft crashes.

**To Reproduce**
1. Download Music Triggers, The Impossible Library, and Illuminations Forge all for the latest version.
2. Run Minecraft.
3. Crash

**Additional context**
[crash-2023-03-09_18.39.58-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/10937473/crash-2023-03-09_18.39.58-client.txt)

**Comment by TheComputerizer** [comment] 2023-03-12 05:41
Im going to close this, since even tho its a different mod it seems to be a duplicate of #90 and go into more detail there

**Closed as completed by TheComputerizer** 2023-03-12 05:41 UTC
