### ISSUE TITLE
[1.18.2 Forge] NPE when unpausing the game

### ISSUE THREAD

**Issue by TheGlitch76** [TheComputerizer/Music-Triggers#41] opened 2022-05-11 01:45 UTC
Crash log: https://0x0.st/om_X.txt

This crash occurred after unpausing the game after loading in to a new world. I was unable to reproduce it a second time.

**Comment by TheComputerizer** [comment] 2022-05-17 23:26
Its hard to say where the issue comes from if it isnt reproduceable. Ill leave the issue open for now

**Comment by FreeFull** [comment] 2022-05-31 15:42
https://gist.github.com/FreeFull/bd6bfa1610f559734c451e7393388391 My logs from hitting what seems to be the same issue. Happened in the Bliss modpack, while closing the Advancements screen

**Comment by TheComputerizer** [comment] 2022-06-17 04:02
Might be backwards calling this a duplicate since the other issue was opened later, but its the same as #54 and I want to keep everything regarding the issue there. Ill close this and if people have other comments they can put them on that issue instead

**Closed by TheComputerizer** 2022-06-17 04:02 UTC
Labels: duplicate, forge, 1.18.2, fix confirmed
